// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "image-sync-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "ImageSyncCoreSpec.h"

@interface ImageSyncCore : NSObject <NativeImageSyncCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ImageSyncCore : NSObject <RCTBridgeModule>
#endif

@end