[package]
name = "image-sync-ffi"
version.workspace = true
edition.workspace = true

[lib]
name = "image_sync_ffi"
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
image-sync-core = { path = "../image-sync-core" }
uniffi = "0.29"

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }
