// Generated by uniffi-bindgen-react-native
#include "image-sync-core.h"
#include "generated/image_sync_ffi.hpp"

namespace imagesynccore {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeImageSyncFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}